version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
      typescript:
        patterns:
          - 'typescript'
    commit-message:
      prefix: 'chore(deps)'
    rebase-strategy: 'auto'
