export const pokemonsListHomeMade = [
    {
        id: 903,
        name: 'Poussacha',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/903.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/903.png',
        slug: 'Poussacha',
        type: ['Plante'],
    },
    {
        id: 906,
        name: 'Coiffeton',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/906.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/906.png',
        slug: 'Coiffeton',
        type: ['Eau'],
    },
    {
        id: 909,
        name: 'Chochodile',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/909.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/909.png',
        slug: 'Chochodile',
        type: ['Feu'],
    },
    {
        id: 926,
        name: 'Pâtachiot',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/926.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/926.png',
        slug: 'Patachiot',
        type: ['Feu'],
    },
    {
        id: 938,
        name: 'Têtampoule',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/938.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/938.png',
        slug: 'Tetampoule',
        type: ['Électrik'],
    },
    {
        id: 9999999,
        name: 'Lilliterelle',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9999999.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9999999.png',
        slug: 'Lilliterelle',
        type: ['Insecte'],
    },
    {
        id: 996,
        name: 'Frigodo',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/996.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/996.png',
        slug: 'Frigodo',
        type: ['Glace'],
    },
    {
        id: 10101,
        name: "Sablette d'Alola",
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10101.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10101.png',
        slug: 'SabletteAlola',
        type: ['Glace', 'Acier'],
    },
    {
        id: 10107,
        name: "Miaouss d'Alola",
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10107.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10107.png',
        slug: 'MiaoussAlola',
        type: ['Ténèbres'],
    },
    {
        id: 10109,
        name: "Racaillou d'Alola",
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10109.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10109.png',
        slug: 'RacaillouAlola',
        type: ['Roche', 'Électrik'],
    },
    {
        id: 10161,
        name: 'Miaouss de Galar',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10161.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10161.png',
        slug: 'MiaoussGalar',
        type: ['Acier'],
    },
    {
        id: 10162,
        name: 'Ponyta de Galar',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10162.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10162.png',
        slug: 'PonytaGalar',
        type: ['Psy'],
    },
    {
        id: 10164,
        name: 'Ramoloss de Galar',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10164.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10164.png',
        slug: 'RamolossGalar',
        type: ['Psy'],
    },
    {
        id: 10166,
        name: 'Canarticho de Galar',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10166.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10166.png',
        slug: 'CanartichoGalar',
        type: ['Combat'],
    },
    {
        id: 10180,
        name: 'Limonde de Galar',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10180.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10180.png',
        slug: 'LimondeGalar',
        type: ['Sol', 'Acier'],
    },
    {
        id: 10231,
        name: "Voltorbe d'Hisui",
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10231.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10231.png',
        slug: 'VoltorbeHisui',
        type: ['Électrik', 'Plante'],
    },
    {
        id: 10234,
        name: "Qwilfish d'Hisui",
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10234.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10234.png',
        slug: 'QwilfishHisui',
        type: ['Ténèbres', 'Poison'],
    },
] as const; //satisfies readonly PokemonInterface[];
