export const pokemonsListHomeMade = [
    {
        id: 903,
        name: 'Poussacha',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/903.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/903.png',
        slug: 'Poussacha',
        type: ['Plante'],
    },
    {
        id: 906,
        name: 'Coiffeton',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/906.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/906.png',
        slug: 'Coiffeton',
        type: ['Eau'],
    },
    {
        id: 909,
        name: 'Chochodile',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/909.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/909.png',
        slug: 'Chochodile',
        type: ['Feu'],
    },
    {
        id: 938,
        name: 'Têtampoule',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/938.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/938.png',
        slug: 'Tetampoule',
        type: ['Électrik'],
    },
    {
        id: 9999999,
        name: 'Lilliterelle',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9999999.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9999999.png',
        slug: 'Lilliterelle',
        type: ['Insecte'],
    },
    {
        id: 996,
        name: 'Frigodo',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/996.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/996.png',
        slug: 'Frigodo',
        type: ['Glace'],
    },
    {
        id: 10101,
        name: "Sablette d'Alola",
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10101.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10101.png',
        slug: 'SabletteAlola',
        type: ['Glace', 'Acier'],
    },
    {
        id: 10180,
        name: 'Limonde de Galar',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10180.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10180.png',
        slug: 'LimondeGalar',
        type: ['Sol', 'Acier'],
    },
] as const; //satisfies readonly PokemonInterface[];
