export const familyPokemon = new Map([
    [
        1,
        {
            id: 147,
            name: 'Minidraco',
            slug: 'Minidraco',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png',
            type: ['Dragon'],
            isLegendary: false,
            isMythical: false,
            generation: 1,
            family: 'Minidraco',
        },
    ],
    [
        2,
        {
            id: 246,
            name: 'Embrylex',
            slug: 'Embrylex',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/246.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/246.png',
            type: ['Roche', 'Sol'],
            isLegendary: false,
            isMythical: false,
            generation: 2,
            family: 'Embrylex',
        },
    ],
    [
        4,
        {
            id: 479,
            name: 'Motisma',
            slug: 'Motisma',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/479.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/479.png',
            type: ['Électrik', 'Spectre'],
            isLegendary: false,
            isMythical: false,
            alternatives: {
                Heat: {
                    id: 10008,
                    name: 'Motisma',
                    slug: 'Heat',
                    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10008.png',
                    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10008.png',
                    type: ['Électrik', 'Feu'],
                    isLegendary: false,
                    isMythical: false,
                },
                Wash: {
                    id: 10009,
                    name: 'Motisma',
                    slug: 'Wash',
                    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10009.png',
                    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10009.png',
                    type: ['Électrik', 'Eau'],
                    isLegendary: false,
                    isMythical: false,
                },
                Frost: {
                    id: 10010,
                    name: 'Motisma',
                    slug: 'Frost',
                    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10010.png',
                    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10010.png',
                    type: ['Électrik', 'Glace'],
                    isLegendary: false,
                    isMythical: false,
                },
                Fan: {
                    id: 10011,
                    name: 'Motisma',
                    slug: 'Fan',
                    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10011.png',
                    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10011.png',
                    type: ['Électrik', 'Vol'],
                    isLegendary: false,
                    isMythical: false,
                },
                Mow: {
                    id: 10012,
                    name: 'Motisma',
                    slug: 'Mow',
                    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10012.png',
                    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10012.png',
                    type: ['Électrik', 'Plante'],
                    isLegendary: false,
                    isMythical: false,
                },
            },
            generation: 4,
            family: 'Motisma',
        },
    ],
    [
        3,
        {
            id: 374,
            name: 'Terhal',
            slug: 'Terhal',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/374.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/374.png',
            type: ['Acier', 'Psy'],
            isLegendary: false,
            isMythical: false,
            generation: 3,
            family: 'Terhal',
        },
    ],
    [
        5,
        {
            id: 636,
            name: 'Pyronille',
            slug: 'Pyronille',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/636.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/636.png',
            type: ['Insecte', 'Feu'],
            isLegendary: false,
            isMythical: false,
            generation: 5,
            family: 'Pyronille',
        },
    ],
    [
        6,
        {
            id: 714,
            name: 'Sonistrelle',
            slug: 'Sonistrelle',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/714.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/714.png',
            type: ['Vol', 'Dragon'],
            isLegendary: false,
            isMythical: false,
            generation: 6,
            family: 'Sonistrelle',
        },
    ],
    [
        7,
        {
            id: 806,
            name: 'Pierroteknik',
            slug: 'Pierroteknik',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/806.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/806.png',
            type: ['Feu', 'Spectre'],
            isLegendary: false,
            isMythical: false,
            generation: 7,
            family: 'Pierroteknik',
        },
    ],
    [
        8,
        {
            id: 885,
            name: 'Fantyrm',
            slug: 'Fantyrm',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/885.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/885.png',
            type: ['Dragon', 'Spectre'],
            isLegendary: false,
            isMythical: false,
            generation: 8,
            family: 'Fantyrm',
        },
    ],
    [
        9,
        {
            id: 1023,
            name: 'Chef-de-Fer',
            slug: 'Chef-de-fer',
            image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1023.png',
            sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1023.png',
            type: ['Acier', 'Psy'],
            isLegendary: false,
            isMythical: false,
            generation: 9,
            family: 'Chef-de-fer',
        },
    ],
]);
