export const megaPokemon = [
    {
        id: 10033,
        type: ['Plante', 'Poison'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10033.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10033.png',
        name: 'Florizarre',
    },
    {
        id: 10034,
        type: ['Feu', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10034.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10034.png',
        name: 'Dracaufeu-Y',
    },
    {
        id: 10035,
        type: ['Feu', 'Dragon'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10035.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10035.png',
        name: 'Dracaufeu-X',
    },
    {
        id: 10036,
        type: ['Eau'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10036.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10036.png',
        name: 'Tortank',
    },
    {
        id: 10090,
        type: ['Insecte', 'Poison'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10090.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10090.png',
        name: 'Dardargnan',
    },
    {
        id: 10073,
        type: ['Normal', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10073.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10073.png',
        name: 'Roucarnage',
    },
    {
        id: 10037,
        type: ['Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10037.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10037.png',
        name: 'Alakazam',
    },
    {
        id: 10071,
        type: ['Eau', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10071.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10071.png',
        name: 'Flagadoss',
    },
    {
        id: 10038,
        type: ['Spectre', 'Poison'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10038.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10038.png',
        name: 'Ectoplasma',
    },
    {
        id: 10039,
        type: ['Normal'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10039.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10039.png',
        name: 'Kangourex',
    },
    {
        id: 10040,
        type: ['Insecte', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10040.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10040.png',
        name: 'Scarabrute',
    },
    {
        id: 10041,
        type: ['Eau', 'Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10041.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10041.png',
        name: 'Léviator',
    },
    {
        id: 10042,
        type: ['Roche', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10042.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10042.png',
        name: 'Ptéra',
    },
    {
        id: 10044,
        type: ['Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10044.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10044.png',
        name: 'Mewtwo-Y',
    },
    {
        id: 10043,
        type: ['Psy', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10043.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10043.png',
        name: 'Mewtwo-X',
    },
    {
        id: 10045,
        type: ['Électrik', 'Dragon'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10045.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10045.png',
        name: 'Pharamp',
    },
    {
        id: 10072,
        type: ['Acier', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10072.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10072.png',
        name: 'Steelix',
    },
    {
        id: 10046,
        type: ['Insecte', 'Acier'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10046.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10046.png',
        name: 'Cizayox',
    },
    {
        id: 10047,
        type: ['Insecte', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10047.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10047.png',
        name: 'Scarhino',
    },
    {
        id: 10048,
        type: ['Ténèbres', 'Feu'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10048.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10048.png',
        name: 'Démolosse',
    },
    {
        id: 10049,
        type: ['Roche', 'Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10049.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10049.png',
        name: 'Tyranocif',
    },
    {
        id: 10065,
        type: ['Plante', 'Dragon'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10065.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10065.png',
        name: 'Jungko',
    },
    {
        id: 10050,
        type: ['Feu', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10050.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10050.png',
        name: 'Braségali',
    },
    {
        id: 10064,
        type: ['Eau', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10064.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10064.png',
        name: 'Laggron',
    },
    {
        id: 10051,
        type: ['Psy', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10051.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10051.png',
        name: 'Gardevoir',
    },
    {
        id: 10066,
        type: ['Ténèbres', 'Spectre'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10066.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10066.png',
        name: 'Ténéfix',
    },
    {
        id: 10052,
        type: ['Acier', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10052.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10052.png',
        name: 'Mysdibule',
    },
    {
        id: 10053,
        type: ['Acier'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10053.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10053.png',
        name: 'Galeking',
    },
    {
        id: 10054,
        type: ['Combat', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10054.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10054.png',
        name: 'Charmina',
    },
    {
        id: 10055,
        type: ['Électrik'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10055.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10055.png',
        name: 'Élecsprint',
    },
    {
        id: 10070,
        type: ['Eau', 'Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10070.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10070.png',
        name: 'Sharpedo',
    },
    {
        id: 10087,
        type: ['Feu', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10087.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10087.png',
        name: 'Camérupt',
    },
    {
        id: 10067,
        type: ['Dragon', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10067.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10067.png',
        name: 'Altaria',
    },
    {
        id: 10056,
        type: ['Spectre'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10056.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10056.png',
        name: 'Branette',
    },
    {
        id: 10057,
        type: ['Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10057.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10057.png',
        name: 'Absol',
    },
    {
        id: 10074,
        type: ['Glace'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10074.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10074.png',
        name: 'Oniglali',
    },
    {
        id: 10089,
        type: ['Dragon', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10089.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10089.png',
        name: 'Drattak',
    },
    {
        id: 10076,
        type: ['Acier', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10076.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10076.png',
        name: 'Métalosse',
    },
    {
        id: 10062,
        type: ['Dragon', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10062.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10062.png',
        name: 'Latias',
    },
    {
        id: 10063,
        type: ['Dragon', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10063.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10063.png',
        name: 'Latios',
    },
    {
        id: 10079,
        type: ['Dragon', 'Vol', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10079.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10079.png',
        name: 'Rayquaza',
    },
    {
        id: 10078,
        type: ['Sol', 'Feu', 'Plante'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10078.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10078.png',
        name: 'Groudon',
    },
    {
        id: 10077,
        type: ['Eau', 'Insecte', 'Électrik'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10077.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10077.png',
        name: 'Kyogre',
    },
    {
        id: 10088,
        type: ['Normal', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10088.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10088.png',
        name: 'Lockpin',
    },
    {
        id: 10058,
        type: ['Dragon', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10058.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10058.png',
        name: 'Carchacrok',
    },
    {
        id: 10059,
        type: ['Combat', 'Acier'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10059.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10059.png',
        name: 'Lucario',
    },
    {
        id: 10060,
        type: ['Plante', 'Glace'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10060.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10060.png',
        name: 'Blizzaroi',
    },
    {
        id: 10068,
        type: ['Psy', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10068.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10068.png',
        name: 'Gallame',
    },
    {
        id: 10069,
        type: ['Normal', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10069.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10069.png',
        name: 'Nanméouïe',
    },
    {
        id: 10075,
        type: ['Roche', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10075.png',
        sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10075.png',
        name: 'Diancie',
    },
];
