export const megaPokemon = [
    {
        dexNumber: 10033,
        type: ['Plante', 'Poison'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10033.png',
        name: 'Florizarre',
    },
    {
        dexNumber: 10034,
        type: ['Feu', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10034.png',
        name: 'Dracaufeu-Y',
    },
    {
        dexNumber: 10035,
        type: ['Feu', 'Dragon'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10035.png',
        name: 'Dracaufeu-X',
    },
    {
        dexNumber: 10036,
        type: ['Eau'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10036.png',
        name: 'Tortank',
    },
    {
        dexNumber: 10090,
        type: ['Insecte', 'Poison'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10090.png',
        name: 'Dardargnan',
    },
    {
        dexNumber: 10073,
        type: ['Normal', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10073.png',
        name: 'Roucarnage',
    },
    {
        dexNumber: 10037,
        type: ['Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10037.png',
        name: 'Alakazam',
    },
    {
        dexNumber: 10071,
        type: ['Eau', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10071.png',
        name: 'Flagadoss',
    },
    {
        dexNumber: 10038,
        type: ['Spectre', 'Poison'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10038.png',
        name: 'Ectoplasma',
    },
    {
        dexNumber: 10039,
        type: ['Normal'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10039.png',
        name: 'Kangourex',
    },
    {
        dexNumber: 10040,
        type: ['Insecte', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10040.png',
        name: 'Scarabrute',
    },
    {
        dexNumber: 10041,
        type: ['Eau', 'Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10041.png',
        name: 'Léviator',
    },
    {
        dexNumber: 10042,
        type: ['Roche', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10042.png',
        name: 'Ptéra',
    },
    {
        dexNumber: 10044,
        type: ['Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10044.png',
        name: 'Mewtwo-Y',
    },
    {
        dexNumber: 10043,
        type: ['Psy', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10043.png',
        name: 'Mewtwo-X',
    },
    {
        dexNumber: 10045,
        type: ['Électrik', 'Dragon'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10045.png',
        name: 'Pharamp',
    },
    {
        dexNumber: 10072,
        type: ['Acier', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10072.png',
        name: 'Steelix',
    },
    {
        dexNumber: 10046,
        type: ['Insecte', 'Acier'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10046.png',
        name: 'Cizayox',
    },
    {
        dexNumber: 10047,
        type: ['Insecte', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10047.png',
        name: 'Scarhino',
    },
    {
        dexNumber: 10048,
        type: ['Ténèbres', 'Feu'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10048.png',
        name: 'Démolosse',
    },
    {
        dexNumber: 10049,
        type: ['Roche', 'Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10049.png',
        name: 'Tyranocif',
    },
    {
        dexNumber: 10065,
        type: ['Plante', 'Dragon'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10065.png',
        name: 'Jungko',
    },
    {
        dexNumber: 10050,
        type: ['Feu', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10050.png',
        name: 'Braségali',
    },
    {
        dexNumber: 10064,
        type: ['Eau', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10064.png',
        name: 'Laggron',
    },
    {
        dexNumber: 10051,
        type: ['Psy', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10051.png',
        name: 'Gardevoir',
    },
    {
        dexNumber: 10066,
        type: ['Ténèbres', 'Spectre'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10066.png',
        name: 'Ténéfix',
    },
    {
        dexNumber: 10052,
        type: ['Acier', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10052.png',
        name: 'Mysdibule',
    },
    {
        dexNumber: 10053,
        type: ['Acier'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10053.png',
        name: 'Galeking',
    },
    {
        dexNumber: 10054,
        type: ['Combat', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10054.png',
        name: 'Charmina',
    },
    {
        dexNumber: 10055,
        type: ['Électrik'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10055.png',
        name: 'Élecsprint',
    },
    {
        dexNumber: 10070,
        type: ['Eau', 'Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10070.png',
        name: 'Sharpedo',
    },
    {
        dexNumber: 10087,
        type: ['Feu', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10087.png',
        name: 'Camérupt',
    },
    {
        dexNumber: 10067,
        type: ['Dragon', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10067.png',
        name: 'Altaria',
    },
    {
        dexNumber: 10056,
        type: ['Spectre'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10056.png',
        name: 'Branette',
    },
    {
        dexNumber: 10057,
        type: ['Ténèbres'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10057.png',
        name: 'Absol',
    },
    {
        dexNumber: 10074,
        type: ['Glace'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10074.png',
        name: 'Oniglali',
    },
    {
        dexNumber: 10089,
        type: ['Dragon', 'Vol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10089.png',
        name: 'Drattak',
    },
    {
        dexNumber: 10076,
        type: ['Acier', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10076.png',
        name: 'Métalosse',
    },
    {
        dexNumber: 10062,
        type: ['Dragon', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10062.png',
        name: 'Latias',
    },
    {
        dexNumber: 10063,
        type: ['Dragon', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10063.png',
        name: 'Latios',
    },
    {
        dexNumber: 10079,
        type: ['Dragon', 'Vol', 'Psy'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10079.png',
        name: 'Rayquaza',
    },
    {
        dexNumber: 10078,
        type: ['Sol', 'Feu', 'Plante'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10078.png',
        name: 'Groudon',
    },
    {
        dexNumber: 10077,
        type: ['Eau', 'Insecte', 'Électrik'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10077.png',
        name: 'Kyogre',
    },
    {
        dexNumber: 10088,
        type: ['Normal', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10088.png',
        name: 'Lockpin',
    },
    {
        dexNumber: 10058,
        type: ['Dragon', 'Sol'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10058.png',
        name: 'Carchacrok',
    },
    {
        dexNumber: 10059,
        type: ['Combat', 'Acier'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10059.png',
        name: 'Lucario',
    },
    {
        dexNumber: 10060,
        type: ['Plante', 'Glace'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10060.png',
        name: 'Blizzaroi',
    },
    {
        dexNumber: 10068,
        type: ['Psy', 'Combat'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10068.png',
        name: 'Gallame',
    },
    {
        dexNumber: 10069,
        type: ['Normal', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10069.png',
        name: 'Nanméouïe',
    },
    {
        dexNumber: 10075,
        type: ['Roche', 'Fée'],
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10075.png',
        name: 'Diancie',
    },
];
