import { inject, Injectable } from '@angular/core';
import { Dynamax, Gigamax } from '@entities/pokemon';
import { PokemonRepository } from './pokemon.repository';
@Injectable({
    providedIn: 'root',
})
export class PokemonDynamaxRepository {
    private readonly pokemonRepository: PokemonRepository = inject(PokemonRepository);
    getDynamaxPokemon() {
        const pokemons = this.pokemonRepository.pokemonIndex.byName;
        const result: Dynamax[] = [
            new Gigamax(pokemons.Florizarre, 198, ['Plante']),
            new Dynamax(pokemons.Florizarre, 198, ['Plante']),
            new Gigamax(pokemons.Dracaufeu, 223, ['Feu']),
            new Dynamax(pokemons.Dracaufeu, 223, ['Dragon']),
            new Dynamax(pokemons.Dracaufeu, 223, ['Feu']),
            new Dynamax(pokemons.Dracaufeu, 223, ['Vol']),
            new Gigamax(pokemons.Tortank, 171, ['Eau']),
            new Dynamax(pokemons.Tortank, 171, ['Roche']),
            new Dynamax(pokemons.Tortank, 171, ['Ténèbres']),
            new Dynamax(pokemons.Tortank, 171, ['Eau']),
            new Gigamax(pokemons.Papilusion, 167, ['Insecte']),
            new Dynamax(pokemons.Papilusion, 167, ['Psy']),
            new Dynamax(pokemons.Papilusion, 167, ['Insecte']),
            new Dynamax(pokemons.Alakazam, 271, ['Combat']),
            new Dynamax(pokemons.Alakazam, 271, ['Psy']),
            new Gigamax(pokemons.Mackogneur, 234, ['Combat']),
            new Dynamax(pokemons.Mackogneur, 234, ['Acier']),
            new Dynamax(pokemons.Mackogneur, 234, ['Combat']),
            new Gigamax(pokemons.Ectoplasma, 261, ['Spectre']),
            new Dynamax(pokemons.Ectoplasma, 261, ['Ténèbres']),
            new Dynamax(pokemons.Ectoplasma, 261, ['Spectre']),
            new Gigamax(pokemons.Krabboss, 240, ['Eau']),
            new Dynamax(pokemons.Krabboss, 240, ['Sol']),
            new Dynamax(pokemons.Krabboss, 240, ['Acier']),
            new Dynamax(pokemons.Krabboss, 240, ['Eau']),
            new Gigamax(pokemons.Lokhlass, 165, ['Glace']),
            new Dynamax(pokemons.Aquali, 205, ['Eau']),
            new Dynamax(pokemons.Voltali, 232, ['Électrik']),
            new Dynamax(pokemons.Pyroli, 246, ['Feu']),
            new Dynamax(pokemons.Amonistar, 207, ['Sol']),
            new Dynamax(pokemons.Amonistar, 207, ['Eau']),
            new Dynamax(pokemons.Amonistar, 207, ['Roche']),
            new Dynamax(pokemons.Kabutops, 220, ['Combat']),
            new Dynamax(pokemons.Kabutops, 220, ['Sol']),
            new Dynamax(pokemons.Kabutops, 220, ['Insecte']),
            new Dynamax(pokemons.Kabutops, 220, ['Eau']),
            new Gigamax(pokemons.Ronflex, 190, ['Normal']),
            new Dynamax(pokemons.Artikodin, 192, ['Glace']),
            new Dynamax(pokemons.Electhor, 253, ['Électrik']),
            new Dynamax(pokemons.Sulfura, 251, ['Feu']),
            new Dynamax(pokemons.Sulfura, 251, ['Vol']),
            new Dynamax(pokemons.Mentali, 261, ['Psy']),
            new Dynamax(pokemons.Noctali, 126, ['Ténèbres']),
            new Dynamax(pokemons.Caratroc, 17, ['Insecte']),
            new Dynamax(pokemons.Caratroc, 17, ['Roche']),
            new Dynamax(pokemons.Leuphorie, 129, ['Psy']),
            new Dynamax(pokemons.Leuphorie, 129, ['Normal']),
            new Dynamax(pokemons.Raikou, 241, ['Électrik']),
            new Dynamax(pokemons.Entei, 235, ['Feu']),
            new Dynamax(pokemons.Suicune, 180, ['Normal']),
            new Dynamax(pokemons.Suicune, 180, ['Glace']),
            new Dynamax(pokemons.Suicune, 180, ['Psy']),
            new Dynamax(pokemons.Suicune, 180, ['Ténèbres']),
            new Dynamax(pokemons.Gardevoir, 237, ['Électrik']),
            new Dynamax(pokemons.Gardevoir, 237, ['Plante']),
            new Dynamax(pokemons.Gardevoir, 237, ['Psy']),
            new Dynamax(pokemons.Gardevoir, 237, ['Fée']),
            new Dynamax(pokemons.Tenefix, 141, ['Spectre']),
            new Dynamax(pokemons.Tenefix, 141, ['Ténèbres']),
            new Dynamax(pokemons.Wailord, 175, ['Psy']),
            new Dynamax(pokemons.Wailord, 175, ['Roche']),
            new Dynamax(pokemons.Wailord, 175, ['Eau']),
            new Dynamax(pokemons.Metalosse, 257, ['Insecte']),
            new Dynamax(pokemons.Metalosse, 257, ['Psy']),
            new Dynamax(pokemons.Metalosse, 257, ['Acier']),
            new Dynamax(pokemons.Latias, 228, ['Fée']),
            new Dynamax(pokemons.Latias, 228, ['Psy']),
            new Dynamax(pokemons.Latias, 228, ['Dragon']),
            new Dynamax(pokemons.Latios, 268, ['Psy']),
            new Dynamax(pokemons.Latios, 268, ['Dragon']),
            new Dynamax(pokemons.Phyllali, 216, ['Normal']),
            new Dynamax(pokemons.Phyllali, 216, ['Plante']),
            new Dynamax(pokemons.Givrali, 238, ['Glace']),
            new Dynamax(pokemons.Gallame, 237, ['Fée']),
            new Dynamax(pokemons.Gallame, 237, ['Combat']),
            new Dynamax(pokemons.Gallame, 237, ['Psy']),
            new Dynamax(pokemons.Colombeau, 226, ['Acier']),
            new Dynamax(pokemons.Colombeau, 226, ['Vol']),
            new Dynamax(pokemons.Minotaupe, 255, ['Sol']),
            new Dynamax(pokemons.Minotaupe, 255, ['Acier']),
            new Dynamax(pokemons.Darumacho, 263, ['Normal']),
            new Dynamax(pokemons.Darumacho, 263, ['Feu']),
            new Gigamax(pokemons.Miasmax, 181, ['Poison']),
            new Dynamax(pokemons.Miasmax, 181, ['Normal']),
            new Dynamax(pokemons.Miasmax, 181, ['Insecte']),
            new Dynamax(pokemons.Hexagel, 190, ['Glace']),
            new Dynamax(pokemons.Sepiatroce, 177, ['Vol']),
            new Dynamax(pokemons.Sepiatroce, 177, ['Psy']),
            new Dynamax(pokemons.Nymphali, 203, ['Normal']),
            new Dynamax(pokemons.Nymphali, 203, ['Fée']),
            new Dynamax(pokemons.Sucreine, 222, ['Fée']),
            new Dynamax(pokemons.Sucreine, 222, ['Plante']),
            new Dynamax(pokemons.Quartermac, 222, ['Normal']),
            new Dynamax(pokemons.Quartermac, 222, ['Combat']),
            new Gigamax(pokemons.Gorythmic, 239, ['Plante']),
            new Dynamax(pokemons.Gorythmic, 239, ['Normal']),
            new Dynamax(pokemons.Gorythmic, 239, ['Plante']),
            new Gigamax(pokemons.Pyrobut, 238, ['Feu']),
            new Dynamax(pokemons.Pyrobut, 238, ['Normal']),
            new Dynamax(pokemons.Pyrobut, 238, ['Feu']),
            new Gigamax(pokemons.Lezargus, 262, ['Eau']),
            new Dynamax(pokemons.Lezargus, 262, ['Normal']),
            new Dynamax(pokemons.Lezargus, 262, ['Eau']),
            new Dynamax(pokemons.Rongrigou, 160, ['Plante']),
            new Dynamax(pokemons.Rongrigou, 160, ['Sol']),
            new Dynamax(pokemons.Rongrigou, 160, ['Ténèbres']),
            new Dynamax(pokemons.Rongrigou, 160, ['Normal']),
            new Dynamax(pokemons.Corvaillus, 163, ['Sol']),
            new Dynamax(pokemons.Corvaillus, 163, ['Vol']),
            new Dynamax(pokemons.Corvaillus, 163, ['Acier']),
            new Dynamax(pokemons.Moumouflon, 159, ['Combat']),
            new Dynamax(pokemons.Moumouflon, 159, ['Normal']),
            new Gigamax(pokemons.Salarsen, 224, ['Électrik']),
            new Dynamax(pokemons.Salarsen, 224, ['Électrik']),
            new Dynamax(pokemons.Salarsen, 224, ['Poison']),
            new Dynamax(pokemons.Sorcilence, 237, ['Psy']),
            new Dynamax(pokemons.Sorcilence, 237, ['Fée']),
            new Dynamax(pokemons.Hexadron, 193, ['Combat']),
            new Dynamax(pokemons.Duralugon, 239, ['Dragon']),
            new Dynamax(pokemons.Duralugon, 239, ['Acier']),
            new Dynamax(pokemons.Zacian.alternatives!.Crowned, 332, ['Acier']),
            new Dynamax(pokemons.Zamazenta.alternatives!.Crowned, 250, ['Acier']),
            new Gigamax(pokemons.Ethernatos, 278, ['Dragon']),
            new Dynamax(pokemons.Wushours, 170, ['Combat']),
            new Dynamax(pokemons.Shifours, 254, ['Ténèbres', 'Combat']),
            new Dynamax(pokemons.Shifours.alternatives!['Rapid-strike'], 254, ['Eau', 'Combat']),
            new Gigamax(pokemons.Angoliath, 227, ['Ténèbres']),
            new Dynamax(pokemons.Lugia, 193, ['Psy', 'Dragon']),
            new Dynamax(pokemons.Kicklee, 224, ['Combat']),
            new Dynamax(pokemons.Tygnon, 193, ['Acier', 'Combat']),
            new Dynamax(pokemons.Kaimorse, 182, ['Eau', 'Glace']),
            new Dynamax(pokemons.Draieul, 231, ['Dragon', 'Psy']),
            new Dynamax(pokemons.Gigalithe, 226, ['Roche', 'Sol']),

            new Dynamax(pokemons['Ho-oh'], 239, ['Acier', 'Feu', 'Psy'], false),

            new Gigamax(pokemons.Pikachu, 112, ['Électrik'], false),
            new Gigamax(pokemons.Miaouss, 92, ['Normal'], false),
            new Gigamax(pokemons.Evoli, 104, ['Normal'], false),
            new Gigamax(pokemons.Melmetal, 226, ['Acier'], false),
            new Gigamax(pokemons.Corvaillus, 163, ['Vol'], false),
            new Gigamax(pokemons.Astronelle, 156, ['Psy'], false),
            new Gigamax(pokemons.Torgamord, 213, ['Eau'], false),
            new Gigamax(pokemons.Monthracite, 146, ['Roche'], false),
            new Gigamax(pokemons.Pomdrapi, 214, ['Plante'], false),
            new Gigamax(pokemons.Dratatin, 178, ['Plante'], false),
            new Gigamax(pokemons.Dunaconda, 202, ['Sol'], false),
            new Gigamax(pokemons.Scolocendre, 220, ['Feu'], false),
            new Gigamax(pokemons.Sorcilence, 237, ['Fée'], false),
            new Gigamax(pokemons.Charmilly, 203, ['Fée'], false),
            new Gigamax(pokemons.Pachyradjah, 226, ['Acier'], false),
            new Gigamax(pokemons.Duralugon, 239, ['Dragon'], false),
            new Gigamax(pokemons.Shifours.alternatives!['Single-strike-gmax'], 254, ['Ténèbres'], false),
            new Gigamax(pokemons.Shifours.alternatives!['Rapid-strike-gmax'], 254, ['Eau'], false),
        ];

        return result;
    }
}
