import { TypePokemon } from '@entities/pokemon';

export const damageRelation: [TypePokemon, [TypePokemon, number][]][] = [
    [
        'Acier',
        [
            ['Acier', 0.5],
            ['Combat', 1],
            ['Dragon', 1],
            ['Eau', 0.5],
            ['Électrik', 0.5],
            ['Fée', 2],
            ['Feu', 0.5],
            ['Glace', 2],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 1],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 2],
            ['Sol', 1],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 1],
        ],
    ],
    [
        'Combat',
        [
            ['Acier', 2],
            ['Combat', 1],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 0.5],
            ['Feu', 1],
            ['Glace', 2],
            ['Insecte', 0.5],
            ['Normal', 2],
            ['Plante', 1],
            ['Poison', 0.5],
            ['Psy', 0.5],
            ['Roche', 2],
            ['Sol', 1],
            ['Spectre', 0],
            ['Ténèbres', 2],
            ['Vol', 0.5],
        ],
    ],
    [
        'Dragon',
        [
            ['Acier', 0.5],
            ['Combat', 1],
            ['Dragon', 2],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 0],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 1],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 1],
            ['Sol', 1],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 1],
        ],
    ],
    [
        'Eau',
        [
            ['Acier', 1],
            ['Combat', 1],
            ['Dragon', 0.5],
            ['Eau', 0.5],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 2],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 0.5],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 2],
            ['Sol', 2],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 1],
        ],
    ],
    [
        'Électrik',
        [
            ['Acier', 1],
            ['Combat', 1],
            ['Dragon', 0.5],
            ['Eau', 2],
            ['Électrik', 0.5],
            ['Fée', 1],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 0.5],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 1],
            ['Sol', 0],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 2],
        ],
    ],
    [
        'Fée',
        [
            ['Acier', 0.5],
            ['Combat', 2],
            ['Dragon', 2],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 0.5],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 1],
            ['Poison', 0.5],
            ['Psy', 1],
            ['Roche', 1],
            ['Sol', 1],
            ['Spectre', 1],
            ['Ténèbres', 2],
            ['Vol', 1],
        ],
    ],
    [
        'Feu',
        [
            ['Acier', 2],
            ['Combat', 1],
            ['Dragon', 0.5],
            ['Eau', 0.5],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 0.5],
            ['Glace', 2],
            ['Insecte', 2],
            ['Normal', 1],
            ['Plante', 2],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 0.5],
            ['Sol', 1],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 1],
        ],
    ],
    [
        'Glace',
        [
            ['Acier', 0.5],
            ['Combat', 1],
            ['Dragon', 2],
            ['Eau', 0.5],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 0.5],
            ['Glace', 0.5],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 2],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 1],
            ['Sol', 2],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 2],
        ],
    ],
    [
        'Insecte',
        [
            ['Acier', 0.5],
            ['Combat', 0.5],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 0.5],
            ['Feu', 0.5],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 2],
            ['Poison', 0.5],
            ['Psy', 2],
            ['Roche', 1],
            ['Sol', 1],
            ['Spectre', 0.5],
            ['Ténèbres', 2],
            ['Vol', 0.5],
        ],
    ],
    [
        'Normal',
        [
            ['Acier', 0.5],
            ['Combat', 1],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 1],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 0.5],
            ['Sol', 1],
            ['Spectre', 0],
            ['Ténèbres', 1],
            ['Vol', 1],
        ],
    ],
    [
        'Plante',
        [
            ['Acier', 0.5],
            ['Combat', 1],
            ['Dragon', 0.5],
            ['Eau', 2],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 0.5],
            ['Glace', 1],
            ['Insecte', 0.5],
            ['Normal', 1],
            ['Plante', 0.5],
            ['Poison', 0.5],
            ['Psy', 1],
            ['Roche', 2],
            ['Sol', 2],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 0.5],
        ],
    ],
    [
        'Poison',
        [
            ['Acier', 0],
            ['Combat', 1],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 2],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 2],
            ['Poison', 0.5],
            ['Psy', 1],
            ['Roche', 0.5],
            ['Sol', 0.5],
            ['Spectre', 0.5],
            ['Ténèbres', 1],
            ['Vol', 1],
        ],
    ],
    [
        'Psy',
        [
            ['Acier', 0.5],
            ['Combat', 2],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 1],
            ['Poison', 2],
            ['Psy', 0.5],
            ['Roche', 1],
            ['Sol', 1],
            ['Spectre', 1],
            ['Ténèbres', 0],
            ['Vol', 1],
        ],
    ],
    [
        'Roche',
        [
            ['Acier', 0.5],
            ['Combat', 0.5],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 2],
            ['Glace', 2],
            ['Insecte', 2],
            ['Normal', 1],
            ['Plante', 1],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 1],
            ['Sol', 0.5],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 2],
        ],
    ],
    [
        'Sol',
        [
            ['Acier', 2],
            ['Combat', 1],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 2],
            ['Fée', 1],
            ['Feu', 2],
            ['Glace', 1],
            ['Insecte', 0.5],
            ['Normal', 1],
            ['Plante', 0.5],
            ['Poison', 2],
            ['Psy', 1],
            ['Roche', 2],
            ['Sol', 1],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 0],
        ],
    ],
    [
        'Spectre',
        [
            ['Acier', 1],
            ['Combat', 1],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 1],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 0],
            ['Plante', 1],
            ['Poison', 1],
            ['Psy', 2],
            ['Roche', 1],
            ['Sol', 1],
            ['Spectre', 2],
            ['Ténèbres', 0.5],
            ['Vol', 1],
        ],
    ],
    [
        'Ténèbres',
        [
            ['Acier', 1],
            ['Combat', 0.5],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 1],
            ['Fée', 0.5],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 1],
            ['Normal', 1],
            ['Plante', 1],
            ['Poison', 1],
            ['Psy', 2],
            ['Roche', 1],
            ['Sol', 1],
            ['Spectre', 2],
            ['Ténèbres', 0.5],
            ['Vol', 1],
        ],
    ],
    [
        'Vol',
        [
            ['Acier', 0.5],
            ['Combat', 2],
            ['Dragon', 1],
            ['Eau', 1],
            ['Électrik', 0.5],
            ['Fée', 1],
            ['Feu', 1],
            ['Glace', 1],
            ['Insecte', 2],
            ['Normal', 1],
            ['Plante', 2],
            ['Poison', 1],
            ['Psy', 1],
            ['Roche', 0.5],
            ['Sol', 1],
            ['Spectre', 1],
            ['Ténèbres', 1],
            ['Vol', 1],
        ],
    ],
] as const;
