name: Auto NPM Update (Latest)

on:
  schedule:
    - cron: '0 3 * * 1' # chaque lundi à 3h
  workflow_dispatch:

jobs:
  npm-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Upgrade all dependencies to latest
        run: |
          # Met à jour toutes les deps vers la dernière version (stable)
          deps=$(jq -r '.dependencies // {} | keys[]' package.json)
          devDeps=$(jq -r '.devDependencies // {} | keys[]' package.json)

          for dep in $deps; do
            npm install "$dep@latest" --legacy-peer-deps
          done

          for dep in $devDeps; do
            npm install --save-dev "$dep@latest" --legacy-peer-deps
          done

      - name: Commit updated dependencies
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore(deps): update all dependencies to latest" || echo "Nothing to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update all dependencies to latest'
          title: 'chore(deps): update all dependencies to latest'
          body: |
            This PR was automatically generated to update all dependencies (including Angular) to their latest available versions.
            Please test and review before merging.
          branch: chore/npm-update-${{ github.run_id }}
          delete-branch: true
